### ISSUE TITLE
are primitives not counted?

### ISSUE THREAD

**Issue by legatoo** [msteindorfer/memory-measurer#1]
https://github.com/msteindorfer/memory-measurer/blob/master/src/objectexplorer/ObjectExplorer.java#L57

here use EnumSet.nonof(), which mean do not visit primitive?

**Comment by msteindorfer** [comment]
To my knowledge, there are two traversal implementations:
- [ObjectExplorer](https://github.com/msteindorfer/memory-measurer/blob/master/src/objectexplorer/ObjectExplorer.java), which does not report primitives, and
- [ObjectGraphExplorer](https://github.com/msteindorfer/memory-measurer/blob/master/src/objectexplorer/ObjectGraphMeasurer.java), which also reports primitives.

I personally use one of the two snippets below to measure memory footprints including primitives: 
- `long memoryInBytes = objectexplorer.MemoryMeasurer.measureBytes(objectToMeasure, predicate);`
- `Footprint memoryFootprint = objectexplorer.ObjectGraphMeasurer.measure(objectToMeasure, predicate);`

The first one reports solely the memory footprint whereas the latter gives you also statistics on how many primitives are used (and also upon their types). In both cases the `predicate` parameter is optional.
